# Generated by Django 3.1.1 on 2020-09-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasestatusmodels',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('verified', 'Verified'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], max_length=25),
        ),
    ]
